### ISSUE TITLE
Remove Util.purs and Util.js?

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#13]
Util.purs and Util.js are a bit of a Chesterton Fence for me. They don't seem to be doing anything but I don't know why they are there so I'm reluctant to remove them.

Does anyone know what they are/were for? Can we safely remove them?

**Comment by JordanMartinez** [comment]
The `beginElements` code looks like some initial debug code that was temporarily used to fix something. That can be dropped. The `domToSvgCoordinates` probably should also be dropped because it should exist in one of the `web` repos.

**Comment by JamieBallingall** [comment]
Great. Thanks. This is a breaking change, so closing in favor of #18
