### ISSUE TITLE
Replace unsafeCoerce with coerce

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#14]
At least some of the uses of `unsafeCoerce` could be replaced with the new `coerce` method of the `Coercible` class.

**Comment by JordanMartinez** [comment]
Let's do this!

**Comment by JamieBallingall** [comment]
This should be partially resolved with #26. But we are left with three uses of `unsafeCoerce` in:

- Halogen.Svg.Core.element
- Halogen.Svg.Elements.element
- Halogen.Svg.Attributes.attr

These uses of `unsafeCoerce` are particularly alarming because they reference the internals of Halogen. Halogen could make some internal change which is non-breaking but which would nevertheless break these functions.

My guess is that these definitions were originally copied over from Halogen and then modified. I suspect that modified versions are no longer required and we could use the functions [elementNS](https://pursuit.purescript.org/packages/purescript-halogen/6.1.2/docs/Halogen.HTML.Elements#v:elementNS) and [attr](https://pursuit.purescript.org/packages/purescript-halogen/6.1.2/docs/Halogen.HTML.Properties#v:attr) directly from Halogen.

I'll try this approach and do a little testing. Assuming that works, I'll create the smallest PR I can and perhaps hop on Discord to ask someone with intimate knowledge of Halogen internals to review.
