### ISSUE TITLE
Format with purty

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#15]
PR #5 has been open for a while. I think some of the reluctance to merge might stem from it adding new functionality and, at the same time, reformatting a lot of code -- making it hard to check that the new functionality is doing what we expect.

I like the idea of having the code formatted with purty. I suggest that we have a PR that re-formats everything with purty but does nothing else.

**Comment by JordanMartinez** [comment]
I like the idea of a formatter, but I don't particularly like `purty`. I think there is some cleanup that could be done in this repo, but I'd rather do that by hand rather than with `purty`.

**Comment by JamieBallingall** [comment]
That's fair. I'm not a huge fan of how `purty` formats things either.

Do you have a particular style guide in mind? Or can I just infer the preferred format from the most common way it is currently done?

**Comment by JordanMartinez** [comment]
I don't have a particular style guide in mind other than below:
- use spaces
- don't use hanging indents
- use camelCase
- Put constructors on their own new line (so don't do `data Foo a = A | B | C`)
- Keep content within an 80-char width (unless it's just a bit over and fixing this would be annoying).
