### ISSUE TITLE
Rename everything with underscore convention

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#16]
We try to match the names of things back to SVG. But in SVG, the dash character ("-") is valid in names, whereas in Purescript it is not. We currently use a mixture of camel case (e.g., `strokeWidth`) and underscores (e.g., `font_size`). Strangely, `GlobalEventAttributes` uses neither convention and introduces camel casing (`onKeyPress`) where the SVG has all lower case and no dashes (`onkeypress`).

I propose that we:
1. Pick a convention
2. Implement that convention consistently throughout
3. Rename the events to all lower case

**Comment by JamieBallingall** [comment]
The underscore convention is visually more similar to the SVG and currently more widely implemented in this repo. Changing to camel casing would require renaming more externally used attributes. Give this comment a thumbs up to indicate a preference for underscore convention

**Comment by JamieBallingall** [comment]
The camel case convention is perhaps more widely used across the Purescript ecosystem. Give this comment a thumbs up to indicate a preference for camel case convention.

**Comment by JordanMartinez** [comment]
Let's go with camelCase.

**Comment by JamieBallingall** [comment]
Ok. Closing this in favor of #18, just to make it clear that a decision has been made and that people need not vote.
