### ISSUE TITLE
Make breaking changes

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#18]
Currently we use a mixture of underscores and camel casing. We should switch everything to camel casing for consistency.

This would be a breaking change. In fact, it would be a high impact breaking change that will probably require users to update their code.

**Comment by JamieBallingall** [comment]
There are a bunch of major breaking changes we'd like to make. "Major" in the sense that an ordinary user would likely have to change their code when these changes are released.

Major breaking changes are:
- Changing all the underscore named functions to camel case
- Add a `NoColor` constructor to Color and change uses of `Maybe Color` to `Color`
- Rename `CSSLength(Nil)` to `CSSLength(NoCSSLength)`
- Add a `NoAlign` constructor to `Align` and change uses of `Maybe Align` to `Align`

**Comment by JamieBallingall** [comment]
I was going to break this into "Major" and "Minor" breaking changes but I don't think it is worth the effort to evaluate how likely someone is to use something. So I'll just extend the list here:
- Fix the `class Show` instances of `FontSize`, `CSSLength`, `Orient` and `MarkerUnit`
- Rename `TextAnchor(Start)` and `TextAnchor(End)` to TextAnchor(AnchorStart)` and `TextAnchor(AnchorEnd)` to match `TextAnchor(Middle)`
- Make ADTs for `font-style`, `font-weight`, `font-stretch`, `font-variant`, `stroke-linecap`, `stroke-linejoin` and `stroke-miterlimit`

**Comment by JordanMartinez** [comment]
I'm thinking about the `Maybe CSSLength` to just `CSSLength` change. The benefit of using `Maybe` is that one can provide default values of `Nothing` that are overridden with `Just` values. If we add a 'NoColor' constructor, that stops applying. Not sure if that matters or not in this context, but did want to mention it.

**Comment by JordanMartinez** [comment]
Upon reflection, I don't think the `Nothing` default applies in this case. If one didn't want it, they would not include the property. If one did want the property to not have a color, it would be weird to pas in `Nothing` rather than `NoColor`.

So, ignore my earlier comment.

**Comment by JamieBallingall** [comment]
I've closed a couple of other issues to include the breaking changes here. The current list is now:

1. Changing all the underscore named functions to camel case
2. Add a `NoColor` constructor to `Color` and change uses of `Maybe Color` to `Color`
3. Rename `CSSLength(Nil)` to `CSSLength(NoCSSLength)`
4. Add a `NoAlign` constructor to `Align` and change uses of `Maybe Align` to `Align`
5. Fix the `class Show` instances of `FontSize`, `CSSLength`, `Orient` and `MarkerUnit`
6. Rename `TextAnchor(Start)` and `TextAnchor(End)` to `TextAnchor(AnchorStart)andTextAnchor(AnchorEnd)` to `matchTextAnchor(Middle)`
7. Make ADTs for font-style, font-weight, font-stretch, font-variant, stroke-linecap, stroke-linejoin and stroke-miterlimit
8. Remove `Util.purs` and `Util.js`

Most of the items on that list are fairly straightforward but item 7 is a fairly involved.

I believe the standard way to do this is create a separate branch where we can make all the changes. Maybe we should hold off until we have fixed up a couple of the non-breaking issues first.

**Comment by JordanMartinez** [comment]
I've just pushed changes to `master` that do all but the following for their corresponding reasons:
- 4: `Align` being wrapped in a Maybe actually makes sense in the context in which it is used.
- 5: because `printX` functions can be used in place of `show`.
- 7: because that will take a lot of time

**Comment by JordanMartinez** [comment]
5 and 7 have been done now (except for `font-variant` in 7 because there's a huge number of options).
