### ISSUE TITLE
Create None option within Color

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#19]
Currently, `Color` is defined as
```
data Color = RGB Int Int Int
           | RGBA Int Int Int Number
           | Named String
```
but it is only ever used wrapped in a `Maybe`. Specifically, 
```
fill :: forall r i. Maybe Color -> IProp (fill :: String | r) i
stroke :: forall r i. Maybe Color -> IProp (stroke :: String | r) i
```
which means that `printColor` has a slightly odd type:
```
printColor :: Maybe Color -> String
```
Elsewhere, types have built in "null" constructors. For example, `CSSLength` has `Nil`.

I suggest that we add a `None` option to `Color` and change `printColor` to `Color -> String`.

Similar to #18, this is a high impact breaking change. I.e., a breaking change is that is likely to force users to update their code. As such, I suggest we implement them both in the same PR to reduce the number of high impact breaking change events our users have to deal with.

**Comment by JordanMartinez** [comment]
I support dropping the `Maybe` around `Color` in `printColor`. Since `CSSLength` also has a "no value"-like value, I think `Color` should get a new data constructor called `NoColor`, and `CSSLength`'s `Nil` would become `NoCssLength`, so that one could import and use both in the same file without getting name clashes. On the other hand, `NoCssLength` is rather long.

Thoughts?

**Comment by JamieBallingall** [comment]
I agree. I think `NoColor` and `NoCSSLength` are perfectly fine names. We should also look at `Align`, which is currently used in:
```
preserveAspectRatio :: forall r i. Maybe {x_ :: Align, y_ :: Align} ->
  MeetOrSlice -> IProp (preserveAspectRatio :: String | r) i
```
It would take a slightly more complicated refactor for `Align` but I think it is worth doing. I think a major benefit of this library is that it provides a nice DSL for SVG in Purescript. To the extent that we can have a clean, self-consistent and Purescript-consistent DSL I think that is a benefit.

**Comment by JamieBallingall** [comment]
To move this forward, perhaps we could add `NoColor` and `NoCSSLength` without removing the `Maybe` or `Nil` options. Just a step in the right direction without any breaking changes.

**Comment by JordanMartinez** [comment]
Adding those constructors would be a breaking change because pattern matching would now fail since it would no longer be exhaustive

**Comment by JamieBallingall** [comment]
Ah! You're right. Everything seems to be a breaking change but I guess that's a result of this being a wrapper library and therefore thin.

Closing this issue in favor of the consolidated breaking changes issue (#18).
