### ISSUE TITLE
Print and show

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#22]
Some attribute types have `Show` instances (e.g., `CSSLength`), others have `printX` functions (e.g., `Align`) and others still have both (e.g., `MarkerUnit`).

I propose that every attribute type have a `Show` instance that works the "standard" way. That is, it follows the convention laid out in the `class Show` definition that:
> While not required, it is recommended that for any expression x, the string show x be executable PureScript code which evaluates to the same value as the expression x.

Also there should be a `Print` class:
```
class Print a where
  print :: a -> String
```
and every attribute type should have a `Print` instance.

Having `Print` isn't just a nice naming convention. It would allow the definition of a helper function:
```
mkAttr :: forall r i a. Print a => String -> a -> IProp r i
mkAttr name = attr (AttrName name) <<< print
```
so that most of our attribute definitions would look like:
```
x :: forall r i. Number -> IProp (x :: Number | r) i
x = mkAttr "x"
```

**Comment by JordanMartinez** [comment]
Print also comes with the drawback of incurring a type class dictionary. I'd be against adding that here, especially if it's basically Show only with different conventions.

I do think we should support both a `Show` instance and `printAttrName` function across all ADTs were AttrName is the name of that ADT (or something similar to its name)
