### ISSUE TITLE
Halogen.Svg.Attributes.Path.c  - missing whitespace between some parameters causes incorrect markup

### ISSUE THREAD

**Issue by paulino26** [JordanMartinez/purescript-halogen-svg-elems#31]
c ref x1_ y1_ x2_ y2_ x_ y_ =
  PathCommand $ renderCommand ref "c"
    <> show x1_
    <> ","
    <> show y1_ -- there should be a space after y1_
    <> show x2_
    <> ","
    <> show y2_  -- there should be a space after y2_
    <> show x_
    <> ","
    <> show y_

**Comment by JordanMartinez** [comment]
Care to submit a PR?

**Comment by paulino26** [comment]
Sure - done.

**Comment by JordanMartinez** [comment]
Fix has been released as v5.0.2 and package set PR is pending merge.
