### ISSUE TITLE
Update to purs-0.15 and publish in spago package set?

### ISSUE THREAD

**Issue by Swordlash** [JordanMartinez/purescript-halogen-svg-elems#34]
As in title :)

**Comment by JordanMartinez** [comment]
Feel free to submit a PR ;-)

**Comment by lucasdicioccio** [comment]
Hi, what exactly would this work entail? some takeover/rename/some-CI-hoops or just a PR somewhere (I don't really know PureScript packaging to be fair nor pursuit/spago etiquette)?

As a testimonial: I've just ported some old Purescript code on a home project from purs-0.13 to 0.15 and regarding my use of this package, it took me more time to find this godsend 🙏 fork and the right incantation to let spago use this fork than to port the actual code. So if we can make life easy for future users with "just a PR" let's do it, I'm happy to help if you point me at the right instructions to follow.

**Comment by JordanMartinez** [comment]
Package set PR pending: https://github.com/purescript/package-sets/pull/1160

**Comment by lucasdicioccio** [comment]
Thank you Jordan!
