### ISSUE TITLE
Add polyline and polygon elements

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-halogen-svg-elems#4]
The [Elm Shapes Example](https://elm-lang.org/examples/shapes) contains a `polyline`. The Cookbook port [ShapesHalogenHooks](https://github.com/JordanMartinez/purescript-cookbook/tree/master/recipes/ShapesHalogenHooks) used a path instead.

It would be nice to have `polyline` and, while we are at it, `polygon` elements available.

**Comment by JordanMartinez** [comment]
Closed by 7890b2898c102ee655c9a92104ba967551779386
